import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import NuqsProvider from "@/providers/NuqsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The BlogHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <NextAuthProvider>
            <ThemeProvider>
              <NuqsProvider>
                <Navbar />
                {children}
              </NuqsProvider>
            </ThemeProvider>
          </NextAuthProvider>
        </ReactQueryProvider>

        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
// yang ada di dalam provider maka harus ditaruh di dalam layout
